#! /bin/sh

### Autostart ###
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xrdb /home/andrew/.Xresources
sxhkd &
caffeine &
compton &
wal -R
redshift &
mpd &
polybar main &

### General Stuff ###
bspc monitor -d I II III IV V VI

bspc config border_width           4
bspc config window_gap             15

bspc config split_ratio            0.50
bspc config top_padding            32
bspc config bottom_padding         15
bspc config left_padding           15
bspc config right_padding          15
bspc config borderless_monocle     true
bspc config gapless_monocle        true
bspc config paddingless_monocle    false
bspc config single_monocle         true
bspc config focus_by_distance      true
bspc config history_aware_focus    true
bspc config ignore_ewmh_focus      false

bspc rule -a mpv state=fullscreen
bspc rule -a feh state=fullscreen

### MOUSE ###
bspc config focus_follows_pointer  true
#bspc config pointer_follows_focus true
#bspc config click_to_focus        true
pointer_follows_monitor            false
