#! /bin/sh

### Autostart ###
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xrdb /home/andrew/.Xresources
wal -R 
#mpd &
sxhkd &
caffeine &
#compton &
redshift &
polybar top &

### Individual Rules ###
bspc rule -a mpv state=fullscreen
bspc rule -a feh state=fullscreen

### General Stuff ###
bspc monitor -d I II III IV V VI

bspc config border_width            4
bspc config window_gap              15

bspc config split_ratio             0.50
bspc config top_padding             32
bspc config bottom_padding          15
bspc config left_padding            15
bspc config right_padding           15
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config paddingless_monocle     false
bspc config single_monocle          true
bspc config focus_by_distance       true
bspc config history_aware_focus     true
bspc config ignore_ewmh_focus       false

### Mouse ###
bspc config focus_follows_pointer   true
bspc config pointer_follows_monitor false
#bspc config pointer_follows_focus  true
#bspc config click_to_focus         true

### Colors ###
. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color   "$color1"
bspc config active_border_color   "$color2"
bspc config focused_border_color  "$color15"
bspc config presel_border_color   "$color1"
