#! /bin/sh

### Autostart ###

xsetroot -cursor_name left_ptr

sxhkd &
compton &
wal -R
redshift &
polybar bar &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

### General Stuff ###
bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d trm ffx atm dis vlc

bspc config border_width         4
bspc config window_gap           20

bspc config split_ratio          0.50
bspc config top_padding          20
bspc config bottom_padding       20
bspc config left_padding         20
bspc config right_padding        20
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle  false
bspc config single_monocle       true
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config ignore_ewmh_focus    false

bspc rule -a mpv state=fullscreen
bspc rule -a feh state=fullscreen
#bspc rule -a Thunar state=floating
#bspc rule -a Firefox desktop='^2' follow=on
#bspc rule -a Atom desktop='^3' follow=on
#bspc rule -a discord desktop='^4' follow=on #state=fullscreen
#bspc rule -a Steam desktop='^4' follow=on
#bspc rule -a Gimp desktop='^5' follow=on
#bspc rule -a Termite state=floating follow=on

### MOUSE ###
bspc config focus_follows_pointer true
#bspc config pointer_follows_focus true
#bspc config click_to_focus        true
pointer_follows_monitor           false

